### ISSUE TITLE
Server is going to loose boost status notification

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#140]
Whenever the server is about to lose boost status the bot should post about it into specified channel.

**Comment by ostorc** [comment]
What kind of message do you want to see?

**Comment by pokorj54** [comment]
Oh no, the server is going to lose level. Somebody do something.Or something similar.

**Comment by tenhobi** [comment]
Is this notification shown **after** some subscriptions have ended? Aka the current number of boosters is for example 29 for 3 days? Or does it implies that it will be 29 after 3 days, but for now it is 30+? 🤔

**Comment by pokorj54** [comment]
I think that you can go 3 days with less than 30 boost to maintain lvl 3, so the notification will be sent when the number of boosters goes below this threshold.

**Comment by pokorj54** [comment]
Ok, I was wrong the server has more than 30 boosts now but, discord says it will lose lvl 3 in less than 3 days.

**Comment by tenhobi** [comment]
Hmm, I believe we can only handle and get a number of current subscribers.

**Comment by tenhobi** [comment]
Cannot be done. The API doesn't expose the necessary information. https://github.com/discord/discord-api-docs/issues/1182

**Comment by tenhobi** [comment]
I will try to check this field:

https://discord.com/developers/docs/resources/guild
https://github.com/DSharpPlus/DSharpPlus/blob/2f6f45723c30a64cc201e9492224f3479b58eac9/DSharpPlus/Entities/DiscordGuild.cs#L406-L416

**Comment by sudofox** [comment]
Just a heads up: the "pending level expiration" display is severely messed up and doesn't match Discord's docs. In particular:

- Admins with different timezones will have the perk expiration message offset back/forward relative to...something...(owner timezone?)
- Discord shows the warning 3 days prior to any of your member's nitro expiration/boost expirations that would cause a level loss and removes the level perks at the time of level loss, instead of removing it 3 days _after_ the level is lost -- so you can't know for sure whether or not you're actually going to lose the level. (There's actually conflicting language visible on the same page in your Server Boost Status page when that happens!)

It's pretty wack.
