### ISSUE TITLE
Users need to rejoin server to be able to get message from bot

### ISSUE THREAD

**Issue by ostorc** [fit-ctu-discord/honza-botner#161]
Critical bug. Needs to be fixed ASAP. 

May be caused by cache as pointed out on Discord

**Comment by jirkavrba** [comment]
![kekw.png](https://user-images.githubusercontent.com/14146321/133314061-d27bc527-1dd5-49a4-84ef-c8d349b9e536.png)

**Comment by stepech** [comment]
Seems like this issue: [https://github.com/DSharpPlus/DSharpPlus/issues/581](https://github.com/DSharpPlus/DSharpPlus/issues/581)
Was fixed in [this PR](https://github.com/DSharpPlus/DSharpPlus/pull/644) although I am not quite sure in which version it was implemented. (Edit: It was fixed in the final 4.0.0 release.)
Could be fixed by this method from the issue... or by updating DSharp.
> This could be resolved by adding fallback `Guild#GetUserAsync`

**Comment by ostorc** [comment]
Good point. We are currently on 4.0.0-rc1 (dont ask why...). From what I can see from release notes, updating should be easy without any breaking changes.
