### ISSUE TITLE
Pin post

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#17]
`.pin <post link>` creates a poll for pinning linked post, If the difference of votes is bigger than specified number it will be pinned or discarded depending on the leading option.

**Comment by jirkavrba** [comment]
Or add an option for message to be automatically pinned when having more than X 📌 emotes?

**Comment by pokorj54** [comment]
That seems like a better idea.

**Comment by tenhobi** [comment]
I like the version with 📌 emoji, and having threshold as some variable.

**Comment by ostorc** [comment]
This feature can be implemented easily by https://dsharpplus.github.io/articles/interactivity.html (the first proposal). The second one can be done through the ReactionHandlers, also not hard. @tenhobi, maybe good first issue, to get in touch with project?

**Comment by tenhobi** [comment]
@ostorc I would rather see this issue fixed by the pushpin 📌 threshold overload than using interactivity. From the quick view, interactivity awaits until some timeout next messages and determines something. We might still want to pin messages from history, right?

Also, we can do this so normal people have +1, Staff (or teachers) have +5 and mods have +{threshold} power in the voting. Etc.

**Comment by ostorc** [comment]
Sure, we will go with reactions on post. The thresholds and vote power will be done through config file.

**Comment by ostorc** [comment]
Implemented and deployed from #77
