### ISSUE TITLE
Design permission model

### ISSUE THREAD

**Issue by ostorc** [fit-ctu-discord/honza-botner#4]
Design permission model and have described somewhere.

**Comment by jirkavrba** [comment]
So here is my proposal for the permission model:

1. Each command has a required set of permissions
1. Permissions can be granted either to **everyone**, **user** or **role**
1. Permissions can be denied either to **user** or **role** 
1. In order to execute the command, the user must have grants for all those required permissions (either granted to the user directly or to any of his roles)
1. By default, there are no grants or denials
1. Users with `MANAGE_SERVER` permission automatically pass any permission resolution as granted. 
1. Deny has precedence over grant

This is both trivial to resolve and easy to persist
![image](https://user-images.githubusercontent.com/14146321/88965248-c3d4d500-d2aa-11ea-9547-ae690c837886.png)

**Comment by ostorc** [comment]
Looks good to me. @pokorj54 any thoughts?

**Comment by pokorj54** [comment]
Nice graph, seems okay to me as well.

**Comment by jirkavrba** [comment]
Ok, I will have a look on an implementation prototype and then we can integrate this into HonzaBotner.Discord package probably

**Comment by tenhobi** [comment]
👍

**Comment by jirkavrba** [comment]
So I implemented a prototype:
https://github.com/jirkavrba/Harold/tree/master/src/main/kotlin/dev/vrba/harold/core/permissions

with an example usage here:
https://github.com/jirkavrba/Harold/blob/master/src/main/kotlin/dev/vrba/harold/core/commands/CommandsHandler.kt#L80-L93

**Comment by jirkavrba** [comment]
Hmmm webhooks are not working?

**Comment by ostorc** [comment]
Already done, we will not continue with this issue
